### ISSUE TITLE
Local / User Settings GUI

### ISSUE THREAD

**Issue by mkolar** [pypeclub/pype#1020]
In Pype3.0 user will be able to locally tweak certain pype settings. We need to make a simple GUi to facilitate it. 

Currently planned user settings
- Mongo URL
- Locations of application executables
- Temp Folder
- Active Site
- Remote Site
- Local site roots (per project)

The plan is to store the settings in the DB in a special collection, where each local site will generate its document where all settings will be stored.

**Comment by iLLiCiTiT** [comment]
## Exploration result
- user settings can be split into few categories

### Pype specific
- **Mongo URL**
    - when thought about this setting it is not user setting but setting of pype on user's machine
    - pype must be restarted when changed
    - better would be to have separate pype action not related to user settings
        - this action should be also used when can't connect to already saved mongo

### User's system overrides
- **Locations of application executables** - modify what system settings returns by prepending values in user settings before studio settings
- Should we store only set values and skip not set?
- We should show in gui studio values too because user may not know what is set there.

### User's project overrides
- **Local site roots (per project)** - modify what project settings returns by overriding root values for each key
    - Should be possible to set default project?
- Should we store only set values and skip not set?
- We should show in gui studio values too because user may not know what is set there.
- Should not be possible to add remove any root.
- All must be set? There may be not user specific roots like for delivery purposes. How to solve AVALON_THUMBNAIL_ROOT which is set by environment variable and not by roots?

### Without result
- **Temp Folder** not sure what kind of temp? (rendering or something else?)
- **Active Site**, **Remote Site** - Know nothing about them, are they project specific? When and where will be applied? How will be applied?

**Comment by mkolar** [comment]
I've made a quick mockup for what we need in there based on the current spec. 

**Mongo**
I don't think it needs another place to set it. Keep in mind it is usually set only once in the igniter and this is really for emergency change. In the past year, we had practically no occasions of the need for changing it.

**Applications**
I'd only store values that are set across the board with local settings. And indeed we need to show the studio default values. Probably best to do it the same way as with Default, vs Studio in the main settings changing the colour on whatever has local override.

**Roots**
Should we store only set values and skip not set? - **YES**
We should show in gui studio values too because user may not know what is set there. - **YES**
Must not be possible to add remove any root. - **CORRECT**
All must be set? - **NO**, whatever is not set, take the studio settings
When will be applied? All the time? - Absolutely, this must take precedence in all path settings at all times, for it to be useful

**Temp Folder**
Not crucial right now, but it should replace system temp folder anywhere we use it. Stagin directories, intermediates and so on

**Active/Remote site**
Single selection choice from registered sites. This is a project level setting with possible default of course.

![image](https://user-images.githubusercontent.com/3333008/108511796-ad32b180-72c0-11eb-858f-1eeef664c841.png)

**Comment by iLLiCiTiT** [comment]
Basic logic implemented with https://github.com/pypeclub/pype/pull/1049 .

## TODOs
- modify executable/args of applications in system settings
    - launch arguments should not be stored for each executable but for whole platform
- give user ability to set environments
    - this requires validations and defined keys that user just can't set
- Nicer UI
- auto restart on change of Pype mongo?

**Comment by mkolar** [comment]
I'm closing this issue. Individual addition should be added as their own issues.
