### ISSUE TITLE
Fix resolving of _SCHEMA_DIR 

### ISSUE THREAD

**Issue by kalisp** [pypeclub/pype#1069]

**Comment by iLLiCiTiT** [comment]
## Issue description
- avalon module use global variables that are set with values from environments on import but avalon environments may not be set at the moment yet because they are set with Avalon Module
- the problem is avalon schema (AVALON_SCHEMA env) and avalon's mongo db (AVALON_MONGO, AVALON_TIMEOUT, AVALON_DB envs) these are problem only if `AvalonMongoDB` object is created and used before variables are set

## Possible solutions
- start pype with preprocess like it was in pype 2 (NO)
- get global environments on pype start using the `extractenvironments` command (on each pype execution we would start pype to get environments before we import anything)
- add "change" functions to be able change global values by different value (would be handy for debugging?)
- set the environments earlier in `start.py` before avalon is imported (before pype's module manager is used)
