### ISSUE TITLE
Nuke: workfile template

### ISSUE THREAD

**Issue by 64qam** [pypeclub/pype#1070]
When a work file on a task doesn't exist create automatically one with the correspondent files in it and file name. It should be similar templates to TVP or PS.

**Comment by jezscha** [comment]
so is it correct I read it as > create first version of workfile, then run build workfile and create render write node at the end? @mkolar

**Comment by mkolar** [comment]
This is kind of two tickets in one. 
1. just giving option to create the first workfile (empty, but with correct name and settings) when artist launches a new task, pretty much what we do with template files in other hosts already
2. Populating this file with reads and write. 

1. should be trivial with current tools
2. will need some backend work most likely because we currently can't run creators in the `build workfile` mechanism. 

>I could create an environment variable similarly to open work file panel at the start.

agreed, it should be have the same way.

**Comment by tokejepsen** [comment]
> will need some backend work most likely because we currently can't run creators in the build workfile mechanism.

https://github.com/pypeclub/pype/issues/838

**Comment by iLLiCiTiT** [comment]
> I could create an environment variable similarly to open work file panel at the start.

I would rather use presets (pype 2)/settings (pype 3) than environments. It gives more dynamic ability to turn it on/off per project.

**Comment by mkolar** [comment]
>I would rather use presets (pype 2)/settings (pype 3) than environments. 

in 3.0 certainly. in 2.x though we are already using a mechanism for opening workfiles app and loading the lastest workfiles. might be better to keep that consistent.
