### ISSUE TITLE
Anatomy `{ext}` vs. `{representation}` keys

### ISSUE THREAD

**Issue by mkolar** [pypeclub/pype#85]
<p>At this moment it is used {{</p>
{ext}
<p>}} key in workfiles anatomy and {{</p>
{representation}
<p>}} elsewhere. We should use only <tt>ext</tt> because <tt>representation</tt> is not the same in all cases (e.g. <tt>thumbnail</tt> repre).</p>
<i>[PYPE-652] created by jakub.trllo</i>

**Comment by iLLiCiTiT** [comment]
Also value for `{ext}` should always already contain "dot" (`.ma`, `.nk`, ...) -> In templates we should not use `{subset}.{ext}` but `{subset}{ext}`.

**Comment by mkolar** [comment]
Is that because `splitext` return the value with the `.` by default?

**Comment by iLLiCiTiT** [comment]
Just opened discussion today. We should not care about this only in anatomy templates, but globally in pipeline where we are working with file extensions. In my point of view is dot part of extensions but I don't want to stuck with that opinion, just suggest possible solution of unification because we currently use both variants, with and without dots which is annoying and possible future bug. BTW: In avalon's workfiles are used extensions with dots, so we have to use `.replace("..", ".")` to be sure we're ok.
